/*
 * Artcoded
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionMetadata {
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "allowedParameters", skip_serializing_if = "Option::is_none")]
    pub allowed_parameters: Option<Vec<models::ActionParameter>>,
    #[serde(rename = "defaultCronValue", skip_serializing_if = "Option::is_none")]
    pub default_cron_value: Option<String>,
}

impl ActionMetadata {
    pub fn new() -> ActionMetadata {
        ActionMetadata {
            key: None,
            title: None,
            description: None,
            allowed_parameters: None,
            default_cron_value: None,
        }
    }
}
