/*
 * Artcoded
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdministrativeDocumentSearchCriteria {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "dateBefore", skip_serializing_if = "Option::is_none")]
    pub date_before: Option<String>,
    #[serde(rename = "dateAfter", skip_serializing_if = "Option::is_none")]
    pub date_after: Option<String>,
    #[serde(rename = "bookmarked", skip_serializing_if = "Option::is_none")]
    pub bookmarked: Option<bool>,
}

impl AdministrativeDocumentSearchCriteria {
    pub fn new() -> AdministrativeDocumentSearchCriteria {
        AdministrativeDocumentSearchCriteria {
            id: None,
            tags: None,
            title: None,
            description: None,
            date_before: None,
            date_after: None,
            bookmarked: None,
        }
    }
}
