/*
 * Artcoded
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CurriculumFreemarkerTemplate {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "dateCreation", skip_serializing_if = "Option::is_none")]
    pub date_creation: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "templateUploadId", skip_serializing_if = "Option::is_none")]
    pub template_upload_id: Option<String>,
}

impl CurriculumFreemarkerTemplate {
    pub fn new() -> CurriculumFreemarkerTemplate {
        CurriculumFreemarkerTemplate {
            id: None,
            date_creation: None,
            name: None,
            template_upload_id: None,
        }
    }
}
