/*
 * Artcoded
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DownloadCvRequest {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    #[serde(rename = "phoneNumber", skip_serializing_if = "Option::is_none")]
    pub phone_number: Option<String>,
    #[serde(rename = "htmlContent", skip_serializing_if = "Option::is_none")]
    pub html_content: Option<String>,
    #[serde(rename = "dailyRate", skip_serializing_if = "Option::is_none")]
    pub daily_rate: Option<bool>,
    #[serde(rename = "availability", skip_serializing_if = "Option::is_none")]
    pub availability: Option<bool>,
    #[serde(rename = "dateReceived", skip_serializing_if = "Option::is_none")]
    pub date_received: Option<String>,
}

impl DownloadCvRequest {
    pub fn new() -> DownloadCvRequest {
        DownloadCvRequest {
            id: None,
            email: None,
            phone_number: None,
            html_content: None,
            daily_rate: None,
            availability: None,
            date_received: None,
        }
    }
}

