/*
 * Artcoded
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeeSummary {
    #[serde(rename = "tag", skip_serializing_if = "Option::is_none")]
    pub tag: Option<String>,
    #[serde(rename = "totalHVAT", skip_serializing_if = "Option::is_none")]
    pub total_hvat: Option<f64>,
    #[serde(rename = "totalVAT", skip_serializing_if = "Option::is_none")]
    pub total_vat: Option<f64>,
}

impl FeeSummary {
    pub fn new() -> FeeSummary {
        FeeSummary {
            tag: None,
            total_hvat: None,
            total_vat: None,
        }
    }
}

