/*
 * Artcoded
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileUploadSearchCriteria {
    #[serde(rename = "correlationId", skip_serializing_if = "Option::is_none")]
    pub correlation_id: Option<String>,
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "dateBefore", skip_serializing_if = "Option::is_none")]
    pub date_before: Option<String>,
    #[serde(rename = "dateAfter", skip_serializing_if = "Option::is_none")]
    pub date_after: Option<String>,
    #[serde(rename = "publicResource", skip_serializing_if = "Option::is_none")]
    pub public_resource: Option<bool>,
    #[serde(rename = "originalFilename", skip_serializing_if = "Option::is_none")]
    pub original_filename: Option<String>,
    #[serde(rename = "bookmarked", skip_serializing_if = "Option::is_none")]
    pub bookmarked: Option<bool>,
}

impl FileUploadSearchCriteria {
    pub fn new() -> FileUploadSearchCriteria {
        FileUploadSearchCriteria {
            correlation_id: None,
            id: None,
            date_before: None,
            date_after: None,
            public_resource: None,
            original_filename: None,
            bookmarked: None,
        }
    }
}

