/*
 * Artcoded
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FileUpload {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "creationDate", skip_serializing_if = "Option::is_none")]
    pub creation_date: Option<String>,
    #[serde(rename = "updatedDate", skip_serializing_if = "Option::is_none")]
    pub updated_date: Option<String>,
    #[serde(rename = "contentType", skip_serializing_if = "Option::is_none")]
    pub content_type: Option<String>,
    #[serde(rename = "originalFilename", skip_serializing_if = "Option::is_none")]
    pub original_filename: Option<String>,
    #[serde(rename = "correlationId", skip_serializing_if = "Option::is_none")]
    pub correlation_id: Option<String>,
    #[serde(rename = "extension", skip_serializing_if = "Option::is_none")]
    pub extension: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i64>,
    #[serde(rename = "publicResource", skip_serializing_if = "Option::is_none")]
    pub public_resource: Option<bool>,
    #[serde(rename = "bookmarked", skip_serializing_if = "Option::is_none")]
    pub bookmarked: Option<bool>,
    #[serde(rename = "bookmarkedDate", skip_serializing_if = "Option::is_none")]
    pub bookmarked_date: Option<String>,
    #[serde(rename = "creationDateString", skip_serializing_if = "Option::is_none")]
    pub creation_date_string: Option<String>,
}

impl FileUpload {
    pub fn new() -> FileUpload {
        FileUpload {
            id: None,
            creation_date: None,
            updated_date: None,
            content_type: None,
            original_filename: None,
            correlation_id: None,
            extension: None,
            name: None,
            size: None,
            public_resource: None,
            bookmarked: None,
            bookmarked_date: None,
            creation_date_string: None,
        }
    }
}

