/*
 * Artcoded
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InvoiceFreemarkerTemplate {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "dateCreation", skip_serializing_if = "Option::is_none")]
    pub date_creation: Option<String>,
    #[serde(rename = "updatedDate", skip_serializing_if = "Option::is_none")]
    pub updated_date: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "templateUploadId", skip_serializing_if = "Option::is_none")]
    pub template_upload_id: Option<String>,
    #[serde(rename = "logicalDelete", skip_serializing_if = "Option::is_none")]
    pub logical_delete: Option<bool>,
}

impl InvoiceFreemarkerTemplate {
    pub fn new() -> InvoiceFreemarkerTemplate {
        InvoiceFreemarkerTemplate {
            id: None,
            date_creation: None,
            updated_date: None,
            name: None,
            template_upload_id: None,
            logical_delete: None,
        }
    }
}

