/*
 * Artcoded
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Label {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "colorHex", skip_serializing_if = "Option::is_none")]
    pub color_hex: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "priceHVAT", skip_serializing_if = "Option::is_none")]
    pub price_hvat: Option<f64>,
    #[serde(rename = "vat", skip_serializing_if = "Option::is_none")]
    pub vat: Option<f64>,
    #[serde(rename = "noDefaultPrice", skip_serializing_if = "Option::is_none")]
    pub no_default_price: Option<bool>,
}

impl Label {
    pub fn new() -> Label {
        Label {
            id: None,
            color_hex: None,
            description: None,
            name: None,
            price_hvat: None,
            vat: None,
            no_default_price: None,
        }
    }
}
