/*
 * Artcoded
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MemZaGram {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "createdDate", skip_serializing_if = "Option::is_none")]
    pub created_date: Option<String>,
    #[serde(rename = "updatedDate", skip_serializing_if = "Option::is_none")]
    pub updated_date: Option<String>,
    #[serde(rename = "visible", skip_serializing_if = "Option::is_none")]
    pub visible: Option<bool>,
    #[serde(rename = "dateOfVisibility", skip_serializing_if = "Option::is_none")]
    pub date_of_visibility: Option<String>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "imageUploadId", skip_serializing_if = "Option::is_none")]
    pub image_upload_id: Option<String>,
    #[serde(rename = "thumbnailUploadId", skip_serializing_if = "Option::is_none")]
    pub thumbnail_upload_id: Option<String>,
    #[serde(rename = "viewsCount", skip_serializing_if = "Option::is_none")]
    pub views_count: Option<i64>,
}

impl MemZaGram {
    pub fn new() -> MemZaGram {
        MemZaGram {
            id: None,
            created_date: None,
            updated_date: None,
            visible: None,
            date_of_visibility: None,
            title: None,
            description: None,
            image_upload_id: None,
            thumbnail_upload_id: None,
            views_count: None,
        }
    }
}
