/*
 * Artcoded
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PagedModelPost {
    #[serde(rename = "content", skip_serializing_if = "Option::is_none")]
    pub content: Option<Vec<models::Post>>,
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<Box<models::PageMetadata>>,
}

impl PagedModelPost {
    pub fn new() -> PagedModelPost {
        PagedModelPost {
            content: None,
            page: None,
        }
    }
}
