/*
 * Artcoded
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PersonalInfo {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "dateCreation", skip_serializing_if = "Option::is_none")]
    pub date_creation: Option<String>,
    #[serde(rename = "updatedDate", skip_serializing_if = "Option::is_none")]
    pub updated_date: Option<String>,
    #[serde(rename = "organizationName", skip_serializing_if = "Option::is_none")]
    pub organization_name: Option<String>,
    #[serde(rename = "vatNumber", skip_serializing_if = "Option::is_none")]
    pub vat_number: Option<String>,
    #[serde(
        rename = "organizationAddress",
        skip_serializing_if = "Option::is_none"
    )]
    pub organization_address: Option<String>,
    #[serde(
        rename = "organizationPostCode",
        skip_serializing_if = "Option::is_none"
    )]
    pub organization_post_code: Option<String>,
    #[serde(rename = "organizationCity", skip_serializing_if = "Option::is_none")]
    pub organization_city: Option<String>,
    #[serde(
        rename = "organizationBankAccount",
        skip_serializing_if = "Option::is_none"
    )]
    pub organization_bank_account: Option<String>,
    #[serde(
        rename = "organizationBankBIC",
        skip_serializing_if = "Option::is_none"
    )]
    pub organization_bank_bic: Option<String>,
    #[serde(rename = "countryCode", skip_serializing_if = "Option::is_none")]
    pub country_code: Option<String>,
    #[serde(
        rename = "organizationPhoneNumber",
        skip_serializing_if = "Option::is_none"
    )]
    pub organization_phone_number: Option<String>,
    #[serde(
        rename = "organizationEmailAddress",
        skip_serializing_if = "Option::is_none"
    )]
    pub organization_email_address: Option<String>,
    #[serde(rename = "ceoFullName", skip_serializing_if = "Option::is_none")]
    pub ceo_full_name: Option<String>,
    #[serde(rename = "note", skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    #[serde(rename = "logoUploadId", skip_serializing_if = "Option::is_none")]
    pub logo_upload_id: Option<String>,
    #[serde(rename = "initialUploadId", skip_serializing_if = "Option::is_none")]
    pub initial_upload_id: Option<String>,
    #[serde(rename = "signatureUploadId", skip_serializing_if = "Option::is_none")]
    pub signature_upload_id: Option<String>,
    #[serde(rename = "financeCharge", skip_serializing_if = "Option::is_none")]
    pub finance_charge: Option<f64>,
    #[serde(rename = "maxDaysToPay", skip_serializing_if = "Option::is_none")]
    pub max_days_to_pay: Option<i32>,
    #[serde(rename = "demoMode", skip_serializing_if = "Option::is_none")]
    pub demo_mode: Option<bool>,
    #[serde(rename = "accountants", skip_serializing_if = "Option::is_none")]
    pub accountants: Option<Vec<models::Accountant>>,
    #[serde(rename = "companyNumber", skip_serializing_if = "Option::is_none")]
    pub company_number: Option<String>,
    #[serde(rename = "cleanVatNumber", skip_serializing_if = "Option::is_none")]
    pub clean_vat_number: Option<String>,
}

impl PersonalInfo {
    pub fn new() -> PersonalInfo {
        PersonalInfo {
            id: None,
            date_creation: None,
            updated_date: None,
            organization_name: None,
            vat_number: None,
            organization_address: None,
            organization_post_code: None,
            organization_city: None,
            organization_bank_account: None,
            organization_bank_bic: None,
            country_code: None,
            organization_phone_number: None,
            organization_email_address: None,
            ceo_full_name: None,
            note: None,
            logo_upload_id: None,
            initial_upload_id: None,
            signature_upload_id: None,
            finance_charge: None,
            max_days_to_pay: None,
            demo_mode: None,
            accountants: None,
            company_number: None,
            clean_vat_number: None,
        }
    }
}
