/*
 * Artcoded
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Portfolio {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "dateCreation", skip_serializing_if = "Option::is_none")]
    pub date_creation: Option<String>,
    #[serde(rename = "updatedDate", skip_serializing_if = "Option::is_none")]
    pub updated_date: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "ticks", skip_serializing_if = "Option::is_none")]
    pub ticks: Option<Vec<models::Tick>>,
    #[serde(rename = "principal", skip_serializing_if = "Option::is_none")]
    pub principal: Option<bool>,
}

impl Portfolio {
    pub fn new() -> Portfolio {
        Portfolio {
            id: None,
            date_creation: None,
            updated_date: None,
            name: None,
            ticks: None,
            principal: None,
        }
    }
}

