/*
 * Artcoded
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimesheetSettingsForm {
    #[serde(rename = "maxHoursPerDay", skip_serializing_if = "Option::is_none")]
    pub max_hours_per_day: Option<f64>,
    #[serde(rename = "minHoursPerDay", skip_serializing_if = "Option::is_none")]
    pub min_hours_per_day: Option<f64>,
    #[serde(rename = "clientId", skip_serializing_if = "Option::is_none")]
    pub client_id: Option<String>,
    #[serde(rename = "timesheetId", skip_serializing_if = "Option::is_none")]
    pub timesheet_id: Option<String>,
}

impl TimesheetSettingsForm {
    pub fn new() -> TimesheetSettingsForm {
        TimesheetSettingsForm {
            max_hours_per_day: None,
            min_hours_per_day: None,
            client_id: None,
            timesheet_id: None,
        }
    }
}
