/*
 * Artcoded
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TvaAdvancePayment {
    #[serde(rename = "datePaid", skip_serializing_if = "Option::is_none")]
    pub date_paid: Option<String>,
    #[serde(rename = "advance", skip_serializing_if = "Option::is_none")]
    pub advance: Option<f64>,
}

impl TvaAdvancePayment {
    pub fn new() -> TvaAdvancePayment {
        TvaAdvancePayment {
            date_paid: None,
            advance: None,
        }
    }
}
