/*
 * Artcoded
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ValidateCronExpression200Response {
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<bool>,
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
}

impl ValidateCronExpression200Response {
    pub fn new() -> ValidateCronExpression200Response {
        ValidateCronExpression200Response {
            value: None,
            key: None,
        }
    }
}

